ISCLADE.ZIP is what Bob gave me saying he has implemented the Stephens-Donnelly
Importance sampler which is a major improvement on the Griffiths-Tavare method
with "driving theta"...
 
Leave *.exe files alone as they were compiled by Bob on his windows machine.
constant.exe:    MS-DOS executable (EXE), OS/2 or MS Windows
exp_flat.exe:    MS-DOS executable (EXE), OS/2 or MS Windows
exponential.exe: MS-DOS executable (EXE), OS/2 or MS Windows

I don't remember how I used this program right now...
The answer should be in the bash script files in:
../IS_CLADE.RS/
../gtree90/
../simulate
and figuring out our basic simulation results directory [dont change any thing here!!!!]
$ ls ../simulate/MS_Simul_Data/
EBCoutput             Gr_5                  array_n_30_gt_G.sh    n_03.t_10.r_0.g_0     n_08.t_10.r_0.g_0     n_90.t_10.r_0.g_0
Gr_0                  Gr_50                 array_n_90_gt.sh      n_04.t_10.r_0.g_0     n_09.t_10.r_0.g_0     n_90.t_10.r_0.g_0.tgz
Gr_1                  SFS_SPID              n10sfspack            n_05.t_10.r_0.g_0     n_10.t_10.r_0.g_0     thetasG0
Gr_10                 array_n_10_gt.sh      n90sfspack            n_06.t_10.r_0.g_0     n_30.t_10.r_0.g_0     tmp2~
Gr_100                array_n_30_gt.sh      n_02.t_10.r_0.g_0     n_07.t_10.r_0.g_0     n_4.t_10.r_0.g_0

